FROM python:3.10-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests build-essential && pip install --no-cache-dir --upgrade pip

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

CMD [ "python3", "consumer.py" ]

