FROM python:3.10-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests build-essential \
    default-libmysqlclient-dev && pip install --no-cache-dir --upgrade pip

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

EXPOSE 5000

CMD [ "python3", "server.py" ]

