apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
stringData:
  MAILTRAP_USERNAME: "api"
  MAILTRAP_PASS: "3bc5a23d96a3e314663b0e774003043e"
  TWILIO: "MV6A6G8CU65T4KVXRUF2ZCBL"
type: Opaque